# name: 'Install'
name: '📦️  '
description: 'Localized Install'
author: 'bahutara'

runs:
  using: 'composite'
  steps:
    - name: '📦️  Dependencies'
      id: dependencies
      shell: bash
      run: |
        pnpm install --frozen-lockfile
